###
POST http://localhost:3000/exercise HTTP/1.1
content-type: application/json

{
    "name": "Pull ups",
    "reps": 12,
    "weight": 175,
    "unit": "lbs",
    "date": "October 2024"
}

###
POST http://localhost:3000/exercise HTTP/1.1
content-type: application/json

{
    "name": "Bench Press",
    "reps": 12,
    "weight": 205,
    "unit": "lbs",
    "date": "October 2025"
}


###
POST http://localhost:3000/exercise HTTP/1.1
content-type: application/json

{
    "name": "Deadlift",
    "reps": 12,
    "weight": 305,
    "unit": "lbs",
    "date": "October 2026"
}


###
GET http://localhost:3000/exercise HTTP/1.1

###
GET http://localhost:3000/exercise/634d80014e546acfb1036040


###
PUT http://localhost:3000/exercise/634d96ad3bcd279862eece7d HTTP/1.1
content-type: application/json

{
    "name": "What a great movement",
    "reps": 9876,
    "weight": 67889,
    "unit": "kg",
    "date": "October 32030"
}


###
DELETE http://localhost:3000/exercise/634da123cad8e2f197c42b62 HTTP/1.1